<!doctype html>
<html lang="fr">
<head>
    <meta  charset='UTF-8' name="viewport" content="width=device-width, initial-scale=1">
    <title>Cake Corner</title>
    <!-- utilisation de normalise -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.css">
    <!-- utilisation de bootstrap pour le css -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!--<link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
--><script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js" integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="Css/style.css" />
</head>
<body id="body">
    <div class="container content">
        <header>
            <!--<form action="home" method="post"  class="row conect" accept-charset="utf-8">
                <input type="text" name="user"  placeholder="Login" class="col-xs-12 col-md-2">
                <input type="text" name="user" placeholder="Password" class="col-xs-12 col-md-2">
                <input type="button" value="conect" name="conect" class="col-xs-8 col-md-2 conectButton">
            </form>-->
            <section class="container content">
                <div id="top" class="row">

                    <div id="logo" class="col-xs-12 col-md-3">
                        <a href="Index.php">
                            <img src="img/logo.png" class="img-responsive logo">
                        </a>
                    </div>
                    <div id="headerlogo" class="col-xs-6 col-md-4-offset-2">
                        <h1>Cake Factory</h1>
                        <p><strong>Des gateaux pour toutes les envies.</strong></p>
                    </div>
                </div>
            </section>
            <?php if ($_SESSION['mod']== 'prod') : ?>
                <nav class="navbar nav-default  navi">
                    <ul class="nav navbar-nav nav-file">
                        <li id="refresh" class="list-group-item lihome">
                            <a href="index.php">Accueil</a>
                        </li>
                        <li class="list-group-item lihome">
                            <a href="index.php?action=about">Nous Contacter</a>
                        </li>
                    </ul>
                </nav>
            <?php endif;?>

        </header>
        <main id='content' >
            <section class="container">
                <?php echo $content ; ?>
            </section>
        </main>
        <script src="js/main.js" type="text/javascript" charset="utf-8" ></script>
        <footer>
            <p>site réalisé en HTML5 CCS3 BOOTSTRAP3 PHP5 et JQUERY </p>
        </footer>
    </div>

</body>
</html>
