<div class="col-xs-0 col-md-4"></div>
<div class="col-xs-12 col-md-6">
	<section >
        <p><strong>Nous contacter : </strong></p>
        <adress>
            <strong>Cake factory </strong></br>
            <a href="mailto:#">Nous contacter par mail</a></br>
            Adresse : 21 rue  Cake 00000 Cakeville france France</adress></br>
            Tel : 06 00 00 00 00
        </adress>
    </section>
</div>